name: Run Leaderboard Rewards FE Test

on:
    push:
      branches: ["feature/leaderboard_rewards_part2" ]
    pull_request:
      branches: ["feature/leaderboard_rewards_part2"] 
        
jobs:

    build:
      
        runs-on: ubuntu-latest
    
        strategy:
          matrix:
            node-version: [18.x]
    
        steps:
        
        - name: Checkout repository
          uses: actions/checkout@v2
    
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
            cache-dependency-path: './go1percent/package-lock.json'
    
        - name: Install dependencies
          run: npm install
          working-directory: go1percentTS
          
        - name: Build project
          run: npm run build --if-present
          working-directory: go1percentTS

        - name: Run Leaderboard Rewards FE Test
          run: npx nightwatch ./src/test/Go1PercentFEAutomation/LeaderboardRewards/AddRewardTest.ts --env chrome
          working-directory: go1percentTS
