name: Node.js CI

on:
  push:
    branches: ["feature/leaderboard_rewards_part2" ]
  pull_request:
    branches: ["feature/leaderboard_rewards_part2"] 



jobs:
  build1:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Use the steps from the template
      - name: Custom Steps
        uses: ./.github/workflows/custom-template.yml     
        
      - name: Run Leaderboard Rewards Test
        run: |
          npx nightwatch ./src/test/Go1PercentFEAutomation/LeaderboardRewards/AddRewardTest.ts --env chrome 
          npx nightwatch ./src/test/Go1PercentFEAutomation/LeaderboardRewards/RedeemRewardTest.ts --env chrome
          npx nightwatch ./src/test/Go1PercentFEAutomation/LeaderboardRewards/UpdateRewardTest.ts --env chrome 
        working-directory: go1percentTS