name: Node.js CI

on:
  push:
    branches: ["feature/leaderboard_rewards_part2" ]
  pull_request:
    branches: ["feature/leaderboard_rewards_part2"] 

jobs:
      
  build_leaderboard_rewards:
    uses: ./.github/workflows/template.yml
    with:
      file_name: ./src/test/Go1PercentFEAutomation/LeaderboardRewards/

  build_adminProfile:
    uses: ./.github/workflows/template.yml
    with:
      file_name: ./src/test/Go1PercentFEAutomation/adminProfile/

  build_contribution:
    uses: ./.github/workflows/template.yml
    with:
      file_name: ./src/test/Go1PercentFEAutomation/contribution/

  build_feedbackForm:
    uses: ./.github/workflows/template.yml
    with:
      file_name: ./src/test/Go1PercentFEAutomation/feedbackForm/

  build_helpdesk:
    uses: ./.github/workflows/template.yml
    with:
      file_name: ./src/test/Go1PercentFEAutomation/helpdesk/

  build_knolxSessions:
    uses: ./.github/workflows/template.yml
    with:
      file_name: ./src/test/Go1PercentFEAutomation/knolxSessions/

  build_LeaderBoardSummary:
    uses: ./.github/workflows/template.yml
    with:
      file_name: ./src/test/Go1PercentFEAutomation/LeaderBoardSummary/

  build_ManageMyUpcomingSession:
    uses: ./.github/workflows/template.yml
    with:
      file_name: ./src/test/Go1PercentFEAutomation/ManageMyUpcomingSession/

  build_manageSlot:
    uses: ./.github/workflows/template.yml
    with:
      file_name: ./src/test/Go1PercentFEAutomation/manageSlot/

  build_ManageUpcomingSession:
    uses: ./.github/workflows/template.yml
    with:
      file_name: ./src/test/Go1PercentFEAutomation/ManageUpcomingSession/

  build_myPastSession:
    uses: ./.github/workflows/template.yml
    with:
      file_name: ./src/test/Go1PercentFEAutomation/myPastSession/

  build_myProfile:
    uses: ./.github/workflows/template.yml
    with:
      file_name: ./src/test/Go1PercentFEAutomation/myProfile/

  build_RequestedSession:
    uses: ./.github/workflows/template.yml
    with:
      file_name: ./src/test/Go1PercentFEAutomation/RequestedSession/

  build_techhub:
    uses: ./.github/workflows/template.yml
    with:
      file_name: ./src/test/Go1PercentFEAutomation/techhub/

          