name: Node.js CI

on:
  push:
    branches: ["feature/leaderboard_rewards_part2" ]
  pull_request:
    branches: ["feature/leaderboard_rewards_part2"] 

jobs:
      
      
  build1:
    uses: ./.github/workflows/template.yml
      