name: Node.js CI

on:
  [push, pull_request] 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percentTS

    - name: Install Nightwatch
      run: npm install --save-dev nightwatch
      working-directory: go1percentTS

    - name: Install ChromeDriver
      run: |
        CHROMEDRIVER_VERSION=119.0.0
        npm install chromedriver@$CHROMEDRIVER_VERSION
      working-directory: go1percentTS

    - name: Build project
      run: npm run build --if-present
      working-directory: go1percentTS
  
    - name: Run Leaderboard Rewards Test
      run: |
        npx nightwatch ./src/test/Go1PercentFEAutomation/LeaderboardRewards/AddRewardTest.ts --env chrome 
        npx nightwatch ./src/test/Go1PercentFEAutomation/LeaderboardRewards/RedeemRewardTest.ts --env chrome
        npx nightwatch ./src/test/Go1PercentFEAutomation/LeaderboardRewards/UpdateRewardTest.ts --env chrome 
      working-directory: go1percentTS
  

    