name: Node.js CI

on:
  push:
    branches: ["feature/LeaderBoard_summary" ]
  pull_request:
    branches: ["feature/LeaderBoard_summary"] 

jobs:
      
  leaderboardRewards:
    uses: ./.github/workflows/fearuresTemlate.yml
    with:
      feature_Name: LeaderboardRewards/

  adminProfile:
    uses: ./.github/workflows/fearuresTemlate.yml
    with:
      feature_Name: adminProfile/

  Contribution:
    uses: ./.github/workflows/fearuresTemlate.yml
    with:
      feature_Name: contribution/

  FeedbackForm:
    uses: ./.github/workflows/fearuresTemlate.yml
    with:
      feature_Name: feedbackForm/

  Helpdesk:
    uses: ./.github/workflows/fearuresTemlate.yml
    with:
      feature_Name: helpdesk/

  KnolxSessions:
    uses: ./.github/workflows/fearuresTemlate.yml
    with:
      feature_Name: knolxSessions/

  LeaderBoardSummary:
    uses: ./.github/workflows/fearuresTemlate.yml
    with:
      feature_Name: LeaderBoardSummary/

  ManageMyUpcomingSession:
    uses: ./.github/workflows/fearuresTemlate.yml
    with:
      feature_Name: ManageMyUpcomingSession/

  ManageSlot:
    uses: ./.github/workflows/fearuresTemlate.yml
    with:
      feature_Name: manageSlot/

  ManageUpcomingSession:
    uses: ./.github/workflows/fearuresTemlate.yml
    with:
      feature_Name: ManageUpcomingSession/

  MyPastSession:
    uses: ./.github/workflows/fearuresTemlate.yml
    with:
      feature_Name: myPastSession/

  MyProfile:
    uses: ./.github/workflows/template.yml
    with:
      feature_Name: myProfile/

  RequestedSession:
    uses: ./.github/workflows/fearuresTemlate.yml
    with:
      feature_Name: RequestedSession/

  Techhub:
    uses: ./.github/workflows/fearuresTemlate.yml
    with:
      feature_Name: techhub/

          