name: Node.js CI

on:
  push:
    branches: ["feature/LeaderBoard_summary"]
  pull_request:
    branches: ["feature/LeaderBoard_summary"]

jobs:
  # Define a template for the jobs
  build_template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './go1percent/package-lock.json'
      - name: Install dependencies
        run: npm install
        working-directory: go1percent
      - name: Build project
        run: npm run build --if-present
        working-directory: go1percent
      - name: Run Go1PercentFEAutomation Tests
        run: npx nightwatch --tag ${{ matrix.tag }} -e chrome
        working-directory: go1percent

  # Generate jobs using the template
  build1:
    name: Build and Test #1
    strategy:
      matrix:
        tag: 'adminProfile'
    extends: build_template


  build2:
  name: Build and Test #1
  strategy:
    matrix:
      tag: 'Contibutions'
  extends: build_template  

  build3:
    name: Build and Test #2
    strategy:
      matrix:
        tag: 'feedBackForm'
    extends: build_template

  build4:
    name: Build and Test #2
    strategy:
      matrix:
        tag: 'helpDesk'
    extends: build_template

  build5:
    name: Build and Test #2
    strategy:
      matrix:
        tag: 'knolexsession'
    extends: build_template


   build6:
    name: Build and Test #2
    strategy:
      matrix:
        tag: 'leaderBoardReview'
    extends: build_template

  build7:
    name: Build and Test #2
    strategy:
      matrix:
        tag: 'LeaderBoardSummary'
    extends: build_template

  build8:
    name: Build and Test #2
    strategy:
      matrix:
        tag: 'manageUpcommingSession'
    extends: build_template

  build9:
    name: Build and Test #2
    strategy:
      matrix:
        tag: 'manageSlots'
    extends: build_template  

  build10:
    name: Build and Test #2
    strategy:
      matrix:
        tag: 'manageUpcommingSession'
    extends: build_template  

  build11:
    name: Build and Test #2
    strategy:
      matrix:
        tag: 'myPastSession'
    extends: build_template 

  build12:
    name: Build and Test #2
    strategy:
      matrix:
        tag: 'myProfile'
    extends: build_template  

  build13:
    name: Build and Test #2
    strategy:
      matrix:
        tag: 'requestsession'
    extends: build_template  

  build14:
    name: Build and Test #2
    strategy:
      matrix:
        tag: 'techhub'
    extends: build_template                  


