name: Node.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
  
    - name: Set working directory
      run: cd go1Percent

    - name: Install dependencies
      run: npm ci
      working-directory: go1percent  # Set the working directory to your project folder

    - name: Build project
      run: npm run build --if-present
      working-directory: go1percent  # Set the working directory to your project folder

    - name: Run Go1PercentAPIAutomation Tests
      run: npx nightwatch test/Go1PercentAPIAutomation --env api_testing
      working-directory: go1percent  # Set the working directory to your project folder

    - name: Run Go1PercentFEAutomation Tests
      run: npx nightwatch test/Go1PercentFEAutomation --env chrome
      working-directory: go1percent  # Set the working directory to your project folder

    - name: Run npm test
      run: npm test
      working-directory: go1percent  # Set the working directory to your project folder
