name: Node.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'
    - name: Chrome Upgrade
      run: CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | cut -d. -f1)
          CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
          wget https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

    - name: Install dependencies
      run: npm install
      working-directory: go1percent  

    - name: Build project
      run: npm run build --if-present
      working-directory: go1percent  

    - name: Run Go1PercentAPIAutomation Tests
      run: npx nightwatch test/Go1PercentAPIAutomation --env api_testing
      working-directory: go1percent  

    - name: Run Go1PercentFEAutomation Tests
      run: npx nightwatch test/Go1PercentFEAutomation --env chrome
      working-directory: go1percent  

    - name: Run npm test
      run: npm test
      working-directory: go1percent  
