name: Nightwatch Tests

on:
  workflow_call:
    inputs:
        feature:
            required: true
            type: string

jobs:
  run_nightwatch:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        feature:
          - 'RequestedSession'
          - 'LeaderBoardSummary'
          - 'LeaderboardRewards'
          - 'ManageMyUpcomingSession'
          - 'ManageUpcomingSession'
          - 'adminProfile'
          - 'contribution'
          - 'feedbackForm'
          - 'helpdesk'
          - 'knolxSessions'
          - 'manageSlot'
          - 'myPastSession'
          - 'myProfile'
          - 'techhub'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './go1percent/package-lock.json'

      - name: Install dependencies
        run: npm install
        working-directory: go1percentTS

      - name: Install Nightwatch
        run: npm install --save-dev nightwatch
        working-directory: go1percentTS

      - name: Install ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=119.0.0
          npm install chromedriver@$CHROMEDRIVER_VERSION
        working-directory: go1percentTS

      - name: Build project
        run: npm run build --if-present
        working-directory: go1percentTS

      - name: Run Frontend Tests:Google Chrome 
        run: npx nightwatch ./src/test/Go1PercentFEAutomation/${{ matrix.feature }} --env chrome
        working-directory: go1percentTS

      - name: Run Frontend Tests:Microsoft Edge 
        run: npx nightwatch ./src/test/Go1PercentFEAutomation/${{ matrix.feature }} --env edge
        working-directory: go1percentTS

      - name: Run Frontend Tests:Firefox 
        run: npx nightwatch ./src/test/Go1PercentFEAutomation/${{ matrix.feature }} --env firefox
        working-directory: go1percentTS
