name: Node.js CI

on:
  push:
    branches: ["feature/My_Past_Session" ]
  pull_request:
    branches: ["feature/My_Past_Session"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percentTS
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percentTS 

    # - name: Run Go1PercentAPIAutomation Tests
    #   run: npx nightwatch  ./test/Go1PercentAPIAutomation/myPastSession/myPastSession.js --env api_testing
    #   working-directory: go1percentTS

    - name: Run Go1PercentFEAutomation Tests
      run: npx nightwatch ./src/test/Go1PercentFEAutomation/myPastSession/myPastSessionFe.ts --env chrome
      working-directory: go1percentTS
