name: Node.js CI

on:
  push:
    branches: ["feature/LeaderBoard_summary" ]
  pull_request:
    branches: ["feature/LeaderBoard_summary"]

jobs:
  adminProfile:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percentTS
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percentTS 

    - name: Run Go1PercentFEAutomation Tests
<<<<<<< HEAD
<<<<<<< HEAD
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/knolxSessions -e edge

=======
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/knolxSessions --env chrome
>>>>>>> 1e6284fa (Update Go1Percent.yml)
=======
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/adminProfile --env chrome
>>>>>>> 6072762239bcb1c2fc89b06bace5c3ba095e75d0
      working-directory: go1percentTS  

  contribution:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percentTS
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percentTS  

    - name: Run Go1PercentFEAutomation Tests
<<<<<<< HEAD
      run: npx nightwatch --tag Contibutions -e chrome
=======
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/contribution --env chrome
>>>>>>> 6072762239bcb1c2fc89b06bace5c3ba095e75d0
      working-directory: go1percentTS 

  feedbackForm:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percentTS
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percentTS  

    - name: Run Go1PercentFEAutomation Tests
<<<<<<< HEAD
      run: npx nightwatch --tag feedBackForm   -e chrome
=======
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/feedbackForm --env chrome
>>>>>>> 6072762239bcb1c2fc89b06bace5c3ba095e75d0
      working-directory: go1percentTS       

  helpdesk:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percentTS
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percentTS  

    - name: Run Go1PercentFEAutomation Tests
<<<<<<< HEAD
      run: npx nightwatch --tag helpDesk -e chrome
=======
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/helpdesk --env chrome
>>>>>>> 6072762239bcb1c2fc89b06bace5c3ba095e75d0
      working-directory: go1percentTS   

  knolxSessions:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percentTS
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percentTS  

    - name: Run Go1PercentFEAutomation Tests
<<<<<<< HEAD
      run: npx nightwatch --tag knolexsession -e chrome
=======
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/knolxSessions --env chrome
>>>>>>> 6072762239bcb1c2fc89b06bace5c3ba095e75d0
      working-directory: go1percentTS    

  LeaderBoardSummary:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percentTS
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percentTS  

    - name: Run Go1PercentFEAutomation Tests
<<<<<<< HEAD
      run: npx nightwatch --tag leaderBoardReview -e chrome
=======
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/LeaderBoardSummary --env chrome
>>>>>>> 6072762239bcb1c2fc89b06bace5c3ba095e75d0
      working-directory: go1percentTS    

  ManageMyUpcomingSession:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percentTS
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percentTS  

    - name: Run Go1PercentFEAutomation Tests
<<<<<<< HEAD
      run: npx nightwatch --tag LeaderBoardSummary -e chrome
=======
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/ManageMyUpcomingSession --env chrome
>>>>>>> 6072762239bcb1c2fc89b06bace5c3ba095e75d0
      working-directory: go1percentTS 

  manageSlot:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percentTS
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percentTS  

    - name: Run Go1PercentFEAutomation Tests
<<<<<<< HEAD
      run: npx nightwatch --tag manageUpcommingSession -e chrome
=======
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/manageSlot --env chrome
>>>>>>> 6072762239bcb1c2fc89b06bace5c3ba095e75d0
      working-directory: go1percentTS  


  ManageUpcomingSession:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percentTS
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percentTS  

    - name: Run Go1PercentFEAutomation Tests
<<<<<<< HEAD
      run: npx nightwatch --tag manageSlots -e chrome
=======
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/ManageUpcomingSession --env chrome
>>>>>>> 6072762239bcb1c2fc89b06bace5c3ba095e75d0
      working-directory: go1percentTS 

  myPastSession:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percentTS
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percentTS  

    - name: Run Go1PercentFEAutomation Tests
<<<<<<< HEAD
      run: npx nightwatch --tag manageUpcommingSession -e chrome
=======
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/myPastSession --env chrome
>>>>>>> 6072762239bcb1c2fc89b06bace5c3ba095e75d0
      working-directory: go1percentTS  

  myProfile:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percentTS
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percentTS  

    - name: Run Go1PercentFEAutomation Tests
<<<<<<< HEAD
      run: npx nightwatch --tag myPastSession -e chrome
=======
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/myProfile --env chrome
>>>>>>> 6072762239bcb1c2fc89b06bace5c3ba095e75d0
      working-directory: go1percentTS   


  RequestedSession:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percentTS
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percentTS  

    - name: Run Go1PercentFEAutomation Tests
<<<<<<< HEAD
      run: npx nightwatch --tag myProfile -e chrome
=======
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/RequestedSession --env chrome
>>>>>>> 6072762239bcb1c2fc89b06bace5c3ba095e75d0
      working-directory: go1percentTS   


  techhub:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percentTS
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percentTS  

    - name: Run Go1PercentFEAutomation Tests
<<<<<<< HEAD
      run: npx nightwatch --tag requestsession -e chrome
=======
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/techhub --env chrome
>>>>>>> 6072762239bcb1c2fc89b06bace5c3ba095e75d0
      working-directory: go1percentTS    


  LeaderboardRewards:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percentTS
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percentTS  

    - name: Run Go1PercentFEAutomation Tests
<<<<<<< HEAD
      run: npx nightwatch --tag techhub -e chrome
=======
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/LeaderboardRewards --env chrome
>>>>>>> 6072762239bcb1c2fc89b06bace5c3ba095e75d0
      working-directory: go1percentTS   
