name: Node.js CI

on:
  push:
    branches: ["feature/LeaderBoard_summary" ]
  pull_request:
    branches: ["feature/LeaderBoard_summary"]

jobs:
  build1:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percent
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percent  

    - name: Run Go1PercentFEAutomation Tests
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/adminProfile -e chrome
      working-directory: go1percent  

  build2:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percent
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percent  

    - name: Run Go1PercentFEAutomation Tests
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/contribution -e chrome
      working-directory: go1percent 

  build3:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percent
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percent  

    - name: Run Go1PercentFEAutomation Tests
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/feedbackForm -e chrome
      working-directory: go1percent       

  build4:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percent
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percent  

    - name: Run Go1PercentFEAutomation Tests
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/helpdesk -e chrome
      working-directory: go1percent   

  build5:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percent
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percent  

    - name: Run Go1PercentFEAutomation Tests
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/knolxSessions -e chrome
      working-directory: go1percent    

  build6:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percent
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percent  

    - name: Run Go1PercentFEAutomation Tests
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/LeaderboardRewards -e chrome
      working-directory: go1percent    

  build7:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percent
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percent  

    - name: Run Go1PercentFEAutomation Tests
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/LeaderBoardSummary -e chrome
      working-directory: go1percent 

  build8:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percent
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percent  

    - name: Run Go1PercentFEAutomation Tests
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/ManageMyUpcomingSession -e chrome
      working-directory: go1percent  


  build9:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percent
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percent  

    - name: Run Go1PercentFEAutomation Tests
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/manageSlot -e chrome
      working-directory: go1percent 

  build10:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percent
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percent  

    - name: Run Go1PercentFEAutomation Tests
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/ManageUpcomingSession -e chrome
      working-directory: go1percent  

  build11:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percent
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percent  

    - name: Run Go1PercentFEAutomation Tests
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/myPastSession -e chrome
      working-directory: go1percent   


  build12:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percent
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percent  

    - name: Run Go1PercentFEAutomation Tests
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/myProfile -e chrome
      working-directory: go1percent   


  build13:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percent
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percent  

    - name: Run Go1PercentFEAutomation Tests
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/RequestedSession -e chrome
      working-directory: go1percent    


  build14:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './go1percent/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: go1percent
      
    - name: Build project
      run: npm run build --if-present
      working-directory: go1percent  

    - name: Run Go1PercentFEAutomation Tests
      run: npx  nightwatch ./src/test/Go1PercentFEAutomation/techhub -e chrome
      working-directory: go1percent   